// Code generated by MockGen. DO NOT EDIT.
// Source: ./rank.go

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	domain "ddd_demo/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRankService is a mock of RankService interface.
type MockRankService struct {
	ctrl     *gomock.Controller
	recorder *MockRankServiceMockRecorder
}

// MockRankServiceMockRecorder is the mock recorder for MockRankService.
type MockRankServiceMockRecorder struct {
	mock *MockRankService
}

// NewMockRankService creates a new mock instance.
func NewMockRankService(ctrl *gomock.Controller) *MockRankService {
	mock := &MockRankService{ctrl: ctrl}
	mock.recorder = &MockRankServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankService) EXPECT() *MockRankServiceMockRecorder {
	return m.recorder
}

// GetTopN mocks base method.
func (m *MockRankService) GetTopN(ctx context.Context) ([]domain.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopN", ctx)
	ret0, _ := ret[0].([]domain.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopN indicates an expected call of GetTopN.
func (mr *MockRankServiceMockRecorder) GetTopN(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopN", reflect.TypeOf((*MockRankService)(nil).GetTopN), ctx)
}

// TopN mocks base method.
func (m *MockRankService) TopN(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopN", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// TopN indicates an expected call of TopN.
func (mr *MockRankServiceMockRecorder) TopN(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopN", reflect.TypeOf((*MockRankService)(nil).TopN), ctx)
}
